### ISSUE TITLE
file_put_contents(xxxx), Failed to open stream: permission denied

### ISSUE THREAD

**Issue by NielsdeBlaauw** [swissspidy/performant-translations#108]
Happens on https://github.com/swissspidy/performant-translations/blob/3defe9327d870c3135f56a3f40191ccf11b2f719/lib/class-performant-translations.php#L162 

The case here is that the WordPress system user does not have write-permission in the plugins directory. 

When a plugin delivers their own translation files (such as https://plugins.trac.wordpress.org/browser/sprinque/trunk/languages), the performant translations plugin tries to write the PHP translation file to the same location. It can't and produces the following warning:

`E_WARNING: file_put_contents(/PATH/TO/WP/CONTENT/plugins/sprinque/languages/sprinque-nl_NL.mo.php): Failed to open stream: Permission denied`

Possible solutions:

1. Check for write permissions on the file, and skip if not available.
2. Always write to the `languages` folder in `wp-content`, regardless of the origin of the original MO file. 
3. Check for permissions to write to the original location, and write to `uploads` or a different - probably writable - location if not allowed.

**Comment by swissspidy** [comment]
Heya, thanks for your report!

If `file_put_contents` fails then it means the prior call to `WP_Filesystem` failed too, which means there is definitely no way for WordPress to write the file in that location. But an `is_writable()` check on the directory can't hurt.

I like the idea of writing to `wp-content/languages` as a fallback, though not sure about another location like the uploads folder. It would make things a bit overly complex for what is more like an edge case.

In your setup, is only the plugins folder not writable? Or others too?

By the way, you can always turn off the file conversion either via `add_filter( 'performant_translations_convert_files', '__return_false' );` or `add_filter( 'performant_translations_preferred_format', static function () { return 'mo'; } );`

----

Aside: If Sprinque is your plugin, you should really leverage the WordPress.org translation system and community instead of bundling translations yourself.

**Comment by NielsdeBlaauw** [comment]
> In your setup, is only the plugins folder not writable? Or others too?
Everything but the `uploads` and `languages` folder in wp-content.

> By the way, you can always turn off the file conversion either via add_filter( 'performant_translations_convert_files', '__return_false' ); or add_filter( 'performant_translations_preferred_format', static function () { return 'mo'; } );
Yeah, the warning doesn't fatal now so we just let it go. This is an exception in an otherwise well working setup and we noticed some good results directly. 

> Aside: If Sprinque is your plugin, you should really leverage the WordPress.org translation system and community instead of bundling translations yourself.
Not my plugin, sadly.

**Comment by swissspidy** [comment]
@NielsdeBlaauw I have a potential fix for this in #109. Could you give it a try to see if it resolves the issues for you?

Here's a ZIP file for testing:

[performant-translations-1.0.7-alpha.zip](https://github.com/swissspidy/performant-translations/files/13205294/performant-translations-1.0.7-alpha.zip)

**Comment by swissspidy** [comment]
@NielsdeBlaauw Friendly ping, have you had a chance to test this version?

**Comment by NielsdeBlaauw** [comment]
Hey @swissspidy 

I did som testing but it doesn't seem to work for me yet. At first I thought it was an incompatbility with loco translate, but after deactivating it, it still doesn't seem to work.

I need to look into it further, but I suspect it's looking for the MO file in the wrong directory in the current setup, as it seems to be looking in `wp-content/languages/plugins/xxx.mo`, where the file is locatied in `wp-content/plugins/languages/xxx.mo` for this case, and only the parsed php file should be moved to the first location.

I'll try and look into it further and figure out exactly what is happening.

**Comment by swissspidy** [comment]
That's great to hear, thanks! Are both projects set up similarly so that I can assume the fix works for both cases?

**Comment by NielsdeBlaauw** [comment]
Hi @swissspidy 

I can confirm it works in the specific cases I was encountering as well.
