### ISSUE TITLE
Cannot redeclare function error with de_DE.php file present

### ISSUE THREAD

**Issue by TobiasBg** [swissspidy/performant-translations#77]
On and old site where I installed the plugin, I had the attached [de_DE.php.txt](https://github.com/swissspidy/performant-translations/files/12527176/de_DE.php.txt) file (I added .txt because GitHub wouldn't accept the file otherwise) in /wp-content/languages/de_DE.php.
(This is/was used to convert German umlauts to more reasonable character sequences, but is now outdated, I think, as WordPress handles this directly now.)

When activating the plugin with this file present, I get an Internal Server Error, due to a function re-declaration, i.e. it appears that this file is being included/required twice.
(In my case, I just got rid of the file, but there might he cases/locales where such a file is still needed/used and where this could lead to problems.)

**Comment by swissspidy** [comment]
Oh... I see! I totally forgot about this archaic functionality in core, but now it rings a bell.

Turns out WP always tries to load `{$locale}.php` if it exists:

https://github.com/WordPress/wordpress-develop/blob/d088e31c73456179502c9bd5354fc43c6267bd7a/src/wp-settings.php#L519-L524

This has been around since forever.

Even if it's probably a bit outdated, this error can still be prevented and backward compatibility maintainted.

I'll need to think about how to best solve this.

The easiest solution is to simply use another file name, e.g. `$locale.mo.php` or something, either for all files or just this case.

An alternative would be to check `get_included_files()` to avoid loading the same file twice. That would prevent the error, as then the plugin would only ever load `de_DE.mo` and never the PHP file. Though it would still first attempt to do so, which is a bit wasteful. Plus it's kinda hacky.

Also need to re-think the uninstall handler, which currently deletes all PHP files in `wp-content/languages`, which in this case might be undesired.
